[colors.primary]
background = "0x262626"

[font]
size = 14.0

[font.normal]
family = "Hack"

[window]
dynamic_padding = true

# this doesn't work on Wayland but oh well
# I'll keep it on in case it starts working one day
resize_increments = true
